apiVersion: v1
kind: Service
metadata:
  name: demo-deployment2
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: demo-deployment2   