name: Publish Docker image to GitHub Container Registry
 
on: [push]

jobs:
  build_tag_push_to_ghcr:
    runs-on: ubuntu-latest
    steps:

      - name: Build and Push Docker Image
        uses: GlueOps/github-actions-build-push-containers@v1.0.0